/**
 * Lector's own systemd unit content is generated by vehicle-server's shared
 * generateSystemdUnit -- this only proves lectorServiceSpec() feeds it the
 * right values, not the generator's own behavior (covered directly in
 * vehicle-server's own test suite).
 */

import { describe, expect, it } from "bun:test";
import { LAUNCH_PROVENANCE_ENV_VAR } from "@danypops/vehicle-server/daemon";
import { generateSystemdUnit } from "@danypops/vehicle-server/service";
import { lectorServiceCli, lectorServiceSpec } from "../src/cli.ts";

describe("Lector systemd service", () => {
	it("targets Armada's native service rather than the obsolete legacy unit", () => {
		expect(lectorServiceCli().unitName).toBe("armada-lector.service");
	});

	it("runs in dynamic-workspaces mode -- a persistent background daemon cannot know upfront which project(s) will attach to it", () => {
		const unit = generateSystemdUnit(lectorServiceSpec());
		expect(unit).toContain("serve");
		expect(unit).toContain("--dynamic-workspaces");
	});

	it('declares "service" launch provenance and restartOnFailure -- Lector\'s own client never auto-spawns, so systemd is its only recovery path', () => {
		const unit = generateSystemdUnit(lectorServiceSpec());
		// vehicle-server 0.3.2 quotes/escapes every Environment= value -- this asserts
		// the quoted form, not the bare one, since that's now the real generated output.
		expect(unit).toContain(`Environment="${LAUNCH_PROVENANCE_ENV_VAR}=service"`);
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("RestartSec=2");
	});
});
