/**
 * Lector's own systemd unit content is generated by vehicle-server's shared
 * generateSystemdUnit -- this only proves lectorServiceSpec() feeds it the
 * right values, not the generator's own behavior (covered directly in
 * vehicle-server's own test suite).
 */

import { describe, expect, it } from "bun:test";
import { LAUNCH_PROVENANCE_ENV_VAR } from "@danypops/vehicle-server/daemon";
import { generateSystemdUnit } from "@danypops/vehicle-server/service";
import { lectorServiceSpec } from "../src/cli.ts";

describe("Lector systemd service", () => {
	it("runs in dynamic-workspaces mode -- a persistent background daemon cannot know upfront which project(s) will attach to it", () => {
		const unit = generateSystemdUnit(lectorServiceSpec());
		expect(unit).toContain("serve");
		expect(unit).toContain("--dynamic-workspaces");
	});

	it('declares "service" launch provenance and restartOnFailure -- Lector\'s own client never auto-spawns, so systemd is its only recovery path', () => {
		const unit = generateSystemdUnit(lectorServiceSpec());
		expect(unit).toContain(`Environment=${LAUNCH_PROVENANCE_ENV_VAR}=service`);
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("RestartSec=2");
	});
});
